kind: pipeline
name: build

steps:
    - name: build-assets
      image: node:lts-alpine
      commands:
      - yarn install --production --no-progress
      - yarn encore production
      
    - name: build-hugo
      image: jojomi/hugo
      commands:
      - hugo -b https://schoolit.mmarnitz.de -d ./output

    - name: deploy
      image: drillster/drone-rsync
      settings:
        hosts:
          from_secret: ssh_host
        key:
          from_secret: ssh_key
        user:
          from_secret: ssh_user
        port:
          from_secret: ssh_port
        source: ./output/
        target: /srv/http/schoolit
        recursive: true
