kind: pipeline
name: build

steps:
    - name: build-assets
      image: node:lts-alpine
      commands:
      - yarn install
      - yarn encore production
      
    - name: build-hugo
      image: jojomi/hugo
      commands:
      - hugo
      environment:
        HUGO_BASEURL: https://schoolit.mmarnitz.de
        HUGO_DESTINATION: /output
