baseURL = "https://schulit.de"
languageCode = "de"
title = "SchulIT"
enableEmoji = true
enableGitInfo = true

[blackfriday]
    hrefTargetBlank = true
    
[taxonomies]
    tag = "tags"
    archive = "archive"

[permalinks]
    tags = "/blog/tags/:slug/"
    archive = "/blog/:slug/"

[[menu.main]]
    identifier = "index"
    name = "Start"
    url = "/"
    weight = -10

[outputs]
    home = [ "HTML", "JSON", "RSS" ]
    section = [ "HTML" ]