baseURL = "https://schulit.de"
languageCode = "de"
title = "SchulIT"
enableEmoji = true
enableGitInfo = true

[blackfriday]
    hrefTargetBlank = true
    
[taxonomies]
    tag = "tags"
    archive = "archives"

[[menu.main]]
    identifier = "index"
    name = "Startseite"
    url = "/"
    weight = -10

[outputs]
    home = [ "HTML", "JSON" ]