name: Build and Deploy
 
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron:  '0 * * * *'
 
jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
 
    - name: Install SSH key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SSH_KEY }}
        name: id_ed25519
        known_hosts: ${{ secrets.KNOWN_HOSTS }}
 
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        submodules: true
 
    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: '0.82.0'
 
    - name: Build
      run: hugo --minify
 
    - name: Copy to server
      run: rsync --delete -rvzh ./public/ github@srv2.mmarnitz.de:/srv/http/schulit